export const productData = [
  {
    ident: 984,
    nom: "THORANI",
    marque: "COSA NUTRA",
    formeGalenique: "Gélule",
    responsable: "UNICORNIO MEDIA LDA",
    doseJournaliere: "2 gélules",
    modeEmploi: "Prendre 2 gélules par jour avec un grand verre d’eau.",
    misesEnGarde:
      "Les compléments alimentaires doivent être utilisés dans le cadre d’un mode de vie sain et ne pas être utilisés comme substituts d’un régime alimentaire varié et équilibré. Ne pas dépasser la dose journalière recommandée. A conserver au frais, au sec et à l'abri de la lumière. Tenir hors de la portée des jeunes enfants. L'emploi est déconseillé chez les femmes enceintes ou allaitantes ainsi que chez les personnes sous antidiabétiques.  Demander conseil à un médecin ou pharmacien pour les enfants.",
    gamme: "",
    aromes: "",
    populationARisques: "Allaitement,Grossesse,Sous antidiabétiques",
    plantes: "Adiantum capillus-veneris L.,Vaccinium myrtillus L.",
    famillePlantes: "",
    partiePlante: "",
    autresIngredients:
      "Levure de bière inactivée,Méthylsulfonate de méthane,D-biotine,maltodextrine,E470b,E464",
    objectifEffets: "Cheveux et ongles",
    image: "https://cdn.pixabay.com/photo/2016/07/26/11/51/capsule-1542682_1280.jpg",
  },
  {
    ident: 985,
    nom: "Altasterol Multivitamin Liquid Capsules",
    marque: "",
    formeGalenique: "Capsule",
    responsable: "ALTA CARE Laboratoires srl",
    doseJournaliere: "1 capsule par jour",
    modeEmploi: "",
    misesEnGarde: "",
    gamme: "",
    aromes: "",
    populationARisques:
      "Allaitement,Enfants en bas âge (1 à 3 ans),Grossesse,Nourrissons (moins de 1 an)",
    plantes: "",
    famillePlantes: "",
    partiePlante: "",
    autresIngredients:
      "Carbonate de calcium,Huile de carthame,Oxyde de magnésium,Acide L-ascorbique,huile de TCM (triglycérides à chaînes moyennes),Fumarate ferreux,monostearate de glycerol,Lécithine,D-alpha-tocophérol,Nicotinamide,Oxyde de zinc,Fluorure de sodium,D-pantothénate de calcium,Sulfate de manganèse,Cyanocobalamine,Chlorhydrate de pyridoxine,Mononitrate de thiamine,Riboflavine,Palmitate de rétinyle,Oxyde de cuivre (II),Cholécalciférol,Acide ptéroylmonoglutamique,Chlorure de chrome,Iodure de potassium,Sélénate de sodium,D-biotine",
    objectifEffets: "Concentration",
    image: "https://cdn.pixabay.com/photo/2015/10/31/12/35/medicine-1015642_1280.jpg",
  },
  {
    ident: 986,
    nom: "CBD",
    marque: "Laboratoires Activa",
    formeGalenique: "Gélule",
    responsable: "LABORATOIRES ACTIVA",
    doseJournaliere: "1 gélule",
    modeEmploi: "1 gélule, une fois par jour, avec un grand verre d’eau en dehors des repas.",
    misesEnGarde:
      "Une consommation excessive peut avoir un effet laxatif. Déconseillé aux femmes enceintes et allaitantes, déconseillé aux enfants adolescents et au moins de 18 ans.",
    gamme: "Bien-être",
    aromes: "",
    populationARisques: "",
    plantes: "Cannabis sativa L.",
    famillePlantes: "Cannabaceae",
    partiePlante: "Graine (huile)",
    autresIngredients: "Arginine,Taurine,E967,E904",
    objectifEffets: "",
    image: "https://cdn.pixabay.com/photo/2017/04/06/08/36/medicine-2207622_1280.jpg",
  },
  {
    ident: 987,
    nom: "COMPLEXE ARTICULATIONS",
    marque: "EAFIT",
    formeGalenique: "Poudre",
    responsable: "EQUILIBRE ATTITUDE",
    doseJournaliere: "14g",
    modeEmploi: "Prendre 14g de poudre diluée dans 250 ml d'eau",
    misesEnGarde:
      "Les compléments alimentaires ne doivent pas se substituer à une alimentation variée et équilibrée et à un mode de vie sain.Ne pas dépasser la dose recommandée. À tenir hors de la portée des jeunes enfants. De manière générale, il est recommandé d’inviter les femmes allaitantes à prendre l’attache d’un professionnel de santé avant toute complémentation. L’emploi chez les femmes enceintes est déconseillé. Demander l’avis de votre médecin et/ou pharmacien (ortie). L’emploi est déconseillé en cas d’ulcères (estomac ou duodenum) ou de calculs biliaires (harpagophytum). La curcumine possède des effets inhibiteurs sur l’agrégation plaquettaire. Elle est déconseillée aux personnes sous anticoagulants",
    gamme: "CONSTRUCTION MUSCULAIRE",
    aromes: "Framboise",
    populationARisques:
      "Autre (à préciser),Grossesse,Problèmes de foie,Sous anticoagulants,Ulcère (estomac ou duodenum)",
    plantes: "Curcuma longa L.,Harpagophytum procumbens,Piper nigrum L.,Prunus avium (L.) L.,Urtica dioica L.",
    famillePlantes: "",
    partiePlante: "",
    autresIngredients:
      "Hydrolysat de collagène bovin,maltodextrine,L-valine,L-leucine,L-isoleucine,Citrate de potassium,E330,Sels calciques de l'acide orthophosphorique,Méthylsulfonate de méthane,Sulfate de chondroïtine,Chlorhydrate de glucosamine,Oxyde de magnésium,E955,Gluconate de cuivre,Cholécalciférol,E322,E414,E551,amidon de maïs modifié,saccharose,huile de tournesol,E307,Triglycérides à chaine moyenne,Arôme - framboise,Arôme agrumes,Arôme",
    objectifEffets: "Articulations,Os,Sport",
    image: "https://cdn.pixabay.com/photo/2014/05/19/00/22/pills-347609_1280.jpg",
  },
  {
    ident: 988,
    nom: "EXTRAIT D’ÉCORCE DE PIN + EXTRAIT DE CYNORRHODON",
    marque: "",
    formeGalenique: "Capsule",
    responsable: "True Nature GmbH",
    doseJournaliere: "1 capsule",
    modeEmploi: "",
    misesEnGarde: "",
    gamme: "",
    aromes: "",
    populationARisques:
      "Adolescents (moins de 18 ans),Allaitement,Enfants (moins de 12 ans),Enfants en bas âge (1 à 3 ans),Grossesse,Nourrissons (moins de 1 an),Enfants (de moins de 6 ans),Enfants (de moins de 10 ans)",
    plantes: "Pinus pinaster Aiton,Rosa canina L.",
    famillePlantes: "",
    partiePlante: "",
    autresIngredients: "E464",
    objectifEffets: "Antioxydant,Artères et cholestérol,Immunité,Ménopause",
    image: "https://cdn.pixabay.com/photo/2015/09/17/01/15/tablets-943765_1280.jpg",
  },
  {
    ident: 800,
    nom: "ERBASTIM",
    marque: "ELFIA NATURE",
    formeGalenique: "Capsule",
    responsable: "SAS ELFIA NATURE",
    doseJournaliere: "3",
    modeEmploi: "",
    misesEnGarde: "",
    gamme: "",
    aromes: "",
    populationARisques:
      "Ulcère (estomac ou duodenum)",
    plantes: "Pinus pinaster Aiton,Rosa canina L.",
    famillePlantes: "",
    partiePlante: "",
    autresIngredients: "E464",
    objectifEffets: "Antioxydant,Artères et cholestérol,Immunité,Ménopause",
    image: "https://www.terravita.fr/media/cache/terravita_product_main_thumbnail_x2/ab/55/c02b21d9d28c5e4e422bb72e902a.png",
  },
];


export const logos = [
  {
    id: 'logo-1',
    description: 'Logo 1',
    image: 'https://www.shadcnblocks.com/images/block/logos/astro.svg',
  },
  {
    id: 'logo-2',
    description: 'Logo 2',
    image: 'https://www.shadcnblocks.com/images/block/logos/figma.svg',
  },
  {
    id: 'logo-3',
    description: 'Logo 3',
    image: 'https://www.shadcnblocks.com/images/block/logos/nextjs.svg',
  },
  {
    id: 'logo-4',
    description: 'Logo 4',
    image: 'https://www.shadcnblocks.com/images/block/logos/react.png',
  },
  {
    id: 'logo-5',
    description: 'Logo 5',
    image: 'https://www.shadcnblocks.com/images/block/logos/shadcn-ui.svg',
  },
  {
    id: 'logo-6',
    description: 'Logo 6',
    image: 'https://www.shadcnblocks.com/images/block/logos/supabase.svg',
  },
  {
    id: 'logo-7',
    description: 'Logo 7',
    image: 'https://www.shadcnblocks.com/images/block/logos/tailwind.svg',
  },
  {
    id: 'logo-8',
    description: 'Logo 8',
    image: 'https://www.shadcnblocks.com/images/block/logos/vercel.svg',
  },
];

export const productsList = [
  {
    id: 'item-1',
    title: 'Product 1',
    summary: 'Description for product 1',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2016/07/26/11/51/capsule-1542682_1280.jpg',
    price: '$19.99',
  },
  {
    id: 'item-2',
    title: 'Product 2',
    summary: 'Description for product 2',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2015/10/31/12/35/medicine-1015642_1280.jpg',
    price: '$29.99',
  },
  {
    id: 'item-3',
    title: 'Product 3',
    summary: 'Description for product 3',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2017/04/06/08/36/medicine-2207622_1280.jpg',
    price: '$39.99',
  },
  {
    id: 'item-4',
    title: 'Product 4',
    summary: 'Description for product 4',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2014/05/19/00/22/pills-347609_1280.jpg',
    price: '$49.99',
  },
  {
    id: 'item-5',
    title: 'Product 5',
    summary: 'Description for product 5',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2015/09/17/01/15/tablets-943765_1280.jpg',
    price: '$59.99',
  },
  {
    id: 'item-6',
    title: 'Product 6',
    summary: 'Description for product 6',
    href: '#',
    image: 'https://cdn.pixabay.com/photo/2015/09/18/21/05/pills-946406_1280.jpg',
    price: '$69.99',
  },
];
